FROM node:20 AS builder

WORKDIR /usr/src/app

RUN npm i -g @nestjs/cli

RUN nest new nestjs --package-manager npm

FROM node:20-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/nestjs .
RUN chown -R node:node /usr/src/app
USER node
EXPOSE 3000
ENTRYPOINT [ "npm", "run" , "start"]
